[package]
name = "attolytics"
version = "0.1.0"
authors = ["Thomas ten Cate <ttencate@gmail.com>"]
edition = "2018"

[dependencies]
clap = "~2.32.0"
rocket = "~0.4.0"
yaml-rust = "~0.4"
postgres = "~0.15"
